version: '3.9'

services:
  to_do_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=to_do
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=to_do
    ports:
      - 5432:5432
  to_do_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - to_do_db


volumes:
  postgres_data: