# Generated by Django 3.2.4 on 2021-06-09 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('complete', models.CharField(choices=[('IN_PROGRESS', 'Выполняется'), ('POSTPONED', 'Отложено'), ('COMPLETE', 'Готово')], default='IN_PROGRESS', max_length=25)),
                ('priority', models.CharField(choices=[('IMPORTANT', 'Важный'), ('UN_IMPORTANT', 'Неважный'), ('VERY_IMPORTANT', 'Очень важный')], default='IMPORTANT', max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-data_created'],
            },
        ),
    ]
