# Generated by Django 3.2.4 on 2021-06-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='complete',
            field=models.CharField(choices=[('POSTPONED', 'Отложено'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETE', 'Готово')], default='IN_PROGRESS', max_length=25),
        ),
        migrations.AlterField(
            model_name='notes',
            name='priority',
            field=models.CharField(choices=[('UN_IMPORTANT', 'Неважный'), ('IMPORTANT', 'Важный'), ('VERY_IMPORTANT', 'Очень важный')], max_length=25),
        ),
    ]
